### ISSUE TITLE
Make the repository a python package and upload the python files for the project.

### ISSUE THREAD

**Issue by datadej** [dostodejski/birthdays_main#1]

**Comment by andrea756** [comment]
I have done the following updates:
 - Uploaded the python files in 0c24f06321c97dc0484ee6964d14436b02a8e92a
 - Created a python package in ce4e0beee41035f467938dea51a2e67d67c716ee
 - Modified the python files to make everything work in 9191290df6b3d70a4f53334612c3cc57ecaec9d2
 - Added a .gitignore file in 51c14d77978eb4a2e3d2bb50c86aa4f3c73c7a75

Closed in 51c14d77978eb4a2e3d2bb50c86aa4f3c73c7a75.
