### ISSUE TITLE
Get dbmanager to parse user values 

### ISSUE THREAD

**Issue by andrea756** [dostodejski/birthdays_main#10]
Now that the dbmanager functions are complete we need argument parsing in order to add or remove users accordingly.

**Comment by andrea756** [comment]
Hi @andrea756, now the dbmanager script works properly. 
I have:
- added the parsing function in ca368ee1daba7f03ee291ceda03d0ee4844ed238.
- updated the main function in 15016bbe46e7a800cef15dcfde64bf139f814fb2.
- make everything work properly in 45b006495d946c471f04ec3c6498ae97083014df.

Closd in 45b006495d946c471f04ec3c6498ae97083014df.

**Comment by datadej** [comment]
Hi @andrea756, now the dbmanager script works properly.
I have:
- added the parsing function in ca368ee.
- updated the main function in 15016bb.
- make everything work properly in 45b0064.
Closed in 45b0064.
