### ISSUE TITLE
Add docstrings to the db manager and check the coding style of the whole project

### ISSUE THREAD

**Issue by GianlucaBasso** [dostodejski/birthdays_main#11]

**Comment by andrea756** [comment]
Now i can close the issue:
- Fixed docstrings in 4a845bd3377e263e8b082a3f94c39917c72d7d92 and d6778d583a3b5c28618edf93756879a8e76ae90c
- Fixed code style in 5fe7897d96adf4aa2a7e3bdb2d8a2d88ec72fb1a

Closed in 5fe7897d96adf4aa2a7e3bdb2d8a2d88ec72fb1a.
