### ISSUE TITLE
Add tests to our project functions

### ISSUE THREAD

**Issue by garbina98** [dostodejski/birthdays_main#12]
We should add tests to the functions and modify them accordingly if they are not working as they should.

**Comment by GianlucaBasso** [comment]
I've created tests_folder and added 2 .py files containing tests for the various modules. In particular:
- Added tests in 71dc7d3bd12b0fe2023f93ce67cd2d93ae5e0c38
- Fixed code style in 6af5d7a27654f8316dbc6ae0d62e2ec1153c5576

Closed in 2b1fada6f594c966ea3065cd64a3f12b6fb42614.
