### ISSUE TITLE
Properly document the code

### ISSUE THREAD

**Issue by andrea756** [dostodejski/birthdays_main#2]
The code is not documented. Please add docstrings to the functions we have in the various python files.

**Comment by datadej** [comment]
Hi Andrea! I've added the following docstrings:
 - for print_birthdays() in 2e869c69f32cc39c7cfbf0e6c0b314b716081316
 - for return_birthdays() in 14a508a1f2388aa8786db7e51e267bf594c1fe54

Closed in 14a508a1f2388aa8786db7e51e267bf594c1fe54.
