### ISSUE TITLE
Use sys module and sys.argv array

### ISSUE THREAD

**Issue by datadej** [dostodejski/birthdays_main#3]

**Comment by GianlucaBasso** [comment]
I have solved the issue:
 - Introduced sys module in 93a41021d51cc4b836c9269fb5e80014ee709a57
 - Updated the return_birthday function and its docstring in ea551fbf5378d197f14930940c1a0fb4be42d61a

Closed in ea551fbf5378d197f14930940c1a0fb4be42d61a.
