### ISSUE TITLE
Fix the coding style

### ISSUE THREAD

**Issue by GianlucaBasso** [dostodejski/birthdays_main#4]
Hi @garbina98 
The coding style of the 2 python files that we have at the moment may not be correct. Please give it a glimpse and let me know if you can solve.

**Comment by garbina98** [comment]
- Fixed the code style in aef09b3573cce94d8f35eaf79e86dae789f9ffd6
- Added some comments in 6ede558088f6a1465a00c8c42a8e53f9a40ee470
Closed in 6ede558088f6a1465a00c8c42a8e53f9a40ee470.
