### ISSUE TITLE
Remove the constants from main.py and use argparse

### ISSUE THREAD

**Issue by garbina98** [dostodejski/birthdays_main#5]

**Comment by garbina98** [comment]
@andrea756 add one positional argument and one optional argument

**Comment by andrea756** [comment]
- Added argument parser in e3d56ad849b9cd8ceae1f894695e4e7c678dfcb5
- Making parsing work properly in 21ca4dd36f3aff1c10563ca057ead35f909b84be
- Added verbosity level in 6db4464f490a5b9a99a1414f8c02b26b50738831

Closed in 6db4464f490a5b9a99a1414f8c02b26b50738831.
