### ISSUE TITLE
Use csv module to read birthdays

### ISSUE THREAD

**Issue by GianlucaBasso** [dostodejski/birthdays_main#6]
We should use the csv module to read retrieve information about people (name and birthday).

**Comment by datadej** [comment]
The problem may be considered as solved my friend :)
- I've added a csv file with the default birthdays in 5562ad5a61c30ac7ef7c8432fccf2b468830ca35
- I've added the needed module support and a python script that reads the data in 6889094181f902d79c1258ce8ded33f29c9584d3

Closed in 6889094181f902d79c1258ce8ded33f29c9584d3.
