### ISSUE TITLE
Add docstrings to the new function, comments and correct code style

### ISSUE THREAD

**Issue by GianlucaBasso** [dostodejski/birthdays_main#7]

**Comment by garbina98** [comment]
@GianlucaBasso as you said, I updated the project according to the following:
- Added new docstrings in 430e3802c356edd10755a8d4dbcea01a035259b3
- Added new comments in ac469f2c55edc9504297fd5916ea529f8e29ab73
- Fixed code style with pycodestyle in e01071f0810d66efe275bb206186525be5756eeb

Closed in e01071f0810d66efe275bb206186525be5756eeb.
