### ISSUE TITLE
Develop the helper code to create a database

### ISSUE THREAD

**Issue by garbina98** [dostodejski/birthdays_main#8]
We should create a database with users (and relative passwords) that are allowed to use the main script and its functions.
We can create it with sqlite3 for python.

**Comment by GianlucaBasso** [comment]
Hi @garbina98!
I think that this is a topic too big to be related only to one issue.
I've created a database managing process in 88a046ddf5d52bd6cc8c52a62ee832f75e7d9eed and solved some minor argument parsing bugs in fb6d0602cba0367515c3b2e37e6244c64895e155.
I will open another issue for the second phase (allowing to add username and password).
Closed in 88a046ddf5d52bd6cc8c52a62ee832f75e7d9eed.
